services:
  # .NET Minimal API
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "${API_PORT:-5001}:${API_INTERNAL_PORT:-8080}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:${API_INTERNAL_PORT:-8080}
    networks:
      - monitoring

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api
    networks:
      - monitoring

  # Log Collector Service
  log-collector:
    build:
      context: ./log-collector
      dockerfile: Dockerfile
    container_name: log-collector
    environment:
      - INFLUXDB_URL=http://influxdb:${INFLUXDB_PORT:-8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-auth-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-my-org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-api-metrics}
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - influxdb
      - nginx
    networks:
      - monitoring
    restart: unless-stopped

  # InfluxDB
  influxdb:
    image: influxdb:2.7
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-my-org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-api-metrics}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-auth-token}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION_PERIOD:-2d}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-81zK2rc4dw0HkEzS}
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - monitoring

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
