apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    database: api-metrics
    user: admin
    secureJsonData:
      token: my-super-secret-auth-token
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: api-metrics
      tlsSkipVerify: true
